apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb
        name: mariadb
        env:
          - name: MARIADB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret
                key: user
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: password
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: persistence-volume
          mountPath: /var/lib/mariadb
      volumes:
      - name: persistence-volume
        persistentVolumeClaim:
          claimName: persistence-volume-claim