apiVersion: apps/v1
kind: Deployment
metadata:
  name: recents-backend
  labels:
    app: recents-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recents-backend
  template:
    metadata:
      labels:
        app: recents-backend
    spec:
      containers:
      - name: recents-backend
        image: ghcr.io/cs-muic/scalable-p1-khingxc/pastebin-backend:latest
        env:
        - name: MARIADB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: secret
              key: user
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: mariadb-url
      imagePullSecrets:
        - name: dockerconfigjson-github-com